-- particle.script
-- This script handles the sampling of a small sub-region of a block texture.
-- It uses the block_id passed in scale.z from the C++ particle engine.

function init(self)
    -- Disable until enabled by C++
    msg.post("#model", "disable")
end

function on_message(self, message_id, message, sender)
    if message_id == hash("enable") then
        local block_id, r, g, b, a, u, v, w, h = voxel_engine.get_particle_init_data(go.get_id())
        
        -- print("Particle Init Data received", go.get_id(), u, v, w, h)

        go.set("#model", "atlas_bounds", vmath.vector4(u, v, w, h))
        model.set_constant("#model", "light_tint", vmath.vector4(r, g, b, a))

        msg.post("#model", "enable")
    elseif message_id == hash("disable") then
        msg.post("#model", "disable")
    end
end
